version: '3.1'
services:
  poiskino1:
    build:
      context: poiskino
      dockerfile: Dockerfile
    networks:
        - poiskino
  poiskino2:
    build:
      context: poiskino
      dockerfile: Dockerfile
    networks:
        - poiskino
  poiskino3:
    build:
      context: poiskino
      dockerfile: Dockerfile
    networks:
        - poiskino
  nginx:
    image: nginx
    ports:
        - 5000:80
    networks:
        - poiskino
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
        - ./localhost.key:/etc/nginx/localhost.key:ro
        - ./localhost.crt:/etc/nginx/localhost.crt:ro
networks:
    poiskino:
        external: false
        name: poiskino