# Generated by Django 3.1.4 on 2020-12-17 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('year', models.PositiveSmallIntegerField(verbose_name='год')),
                ('genre', models.IntegerField(choices=[(1, 'Боевик'), (2, 'Вестерн'), (3, 'Детектив'), (4, 'Документальный'), (5, 'Драма'), (6, 'Комедия'), (7, 'Мелодрама'), (8, 'Мультфильм'), (9, 'Сериал'), (10, 'Триллер'), (11, 'Фантастика')], verbose_name='жанр')),
                ('actors', models.ManyToManyField(to='app.Actor', verbose_name='актеры')),
                ('directors', models.ManyToManyField(to='app.Director', verbose_name='режессеры')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('films', models.ManyToManyField(to='app.Film', verbose_name='фильмы')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='ggenre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.genre'),
        ),
    ]
