# Generated by Django 2.0.4 on 2020-05-11 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('year', models.PositiveSmallIntegerField(verbose_name='год')),
                ('genre', models.IntegerField(choices=[(1, 'Боевик'), (2, 'Вестерн'), (3, 'Детектив'), (4, 'Документальный'), (5, 'Драма'), (6, 'Комедия'), (7, 'Мелодрама'), (8, 'Мультфильм'), (9, 'Сериал'), (10, 'Триллер'), (11, 'Фантастика')], verbose_name='жанр')),
                ('actors', models.ManyToManyField(to='app.Actor', verbose_name='актеры')),
                ('directors', models.ManyToManyField(to='app.Director', verbose_name='режессеры')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Film')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='название')),
                ('films', models.ManyToManyField(to='app.Film', verbose_name='фильмы')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50, unique=True, verbose_name='логин')),
                ('password', models.CharField(max_length=60, verbose_name='пароль')),
            ],
        ),
        migrations.AddField(
            model_name='list',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.User'),
        ),
        migrations.AddField(
            model_name='like',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.User'),
        ),
    ]
