# Generated by Django 2.0.4 on 2020-05-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_list_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='films',
            field=models.ManyToManyField(null=True, to='app.Film', verbose_name='фильмы'),
        ),
    ]
