# Generated by Django 2.0.4 on 2020-05-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200526_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='films',
            field=models.ManyToManyField(to='app.Film', verbose_name='фильмы'),
        ),
    ]
